"""
Copy-ready text versions of a solved problem -- LaTeX source and a plain-text summary -- for the Share
dialog. Streamlit-free.

These are for pasting: into a LaTeX document, an email, a chat, a lab notebook. They contain only what
the app has already computed (the derived equations, the verified numeric answers with their units, the
verification verdict); nothing is generated by a model here.

The LaTeX uses plain `amsmath` (`gather*`, `\\text`) and nothing that needs a particular package beyond
that, and every unit and name is escaped, since a unit like "m/s^2" or a name with an underscore would
otherwise break compilation.
"""
import re

import sympy as sp

from modules.equation_engine import ProblemModel
from modules.solver import SolutionStep
from modules.verifier import VerificationReport

_TEX_SPECIALS = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
                 "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def tex_escape(text: str) -> str:
    """`text` made safe to use inside \\text{...} (or running LaTeX text)."""
    return "".join(_TEX_SPECIALS.get(ch, ch) for ch in text)


def _unit_tex(unit: str | None) -> str:
    """A unit string as LaTeX math: 'm/s^2' -> '\\,\\mathrm{m/s}^{2}'. Falls back to escaped text for
    anything that is not a plain product/quotient of unit names with integer exponents."""
    if not unit or unit.strip().lower() in ("unitless", "dimensionless", "none", "1"):
        return ""
    u = unit.strip().replace("**", "^")
    m = re.fullmatch(r"([A-Za-z°µΩ/\*\s\.\-]+?)\^(-?\d+)", u)
    if m:
        return rf"\,\text{{{tex_escape(m.group(1).strip())}}}^{{{m.group(2)}}}"
    # exponents inside a quotient, e.g. "kg*m/s^2": convert each name^n
    parts = re.split(r"(\^-?\d+)", u)
    out = ""
    for p in parts:
        if re.fullmatch(r"\^-?\d+", p):
            out += "^{" + p[1:] + "}"
        else:
            out += rf"\text{{{tex_escape(p)}}}" if p else ""
    return r"\," + out


def _number_tex(value: float) -> str:
    s = f"{value:.6g}"
    if "e" in s:
        mant, exp = s.split("e")
        return rf"{mant}\times 10^{{{int(exp)}}}"
    return s


def equation_latex_lines(model: ProblemModel) -> list[str]:
    """One LaTeX string per parsed relation; a relation that failed to parse is skipped, not guessed at."""
    return [sp.latex(e.sympy_eq) for e in model.equations if e.sympy_eq is not None]


def answer_latex_lines(model: ProblemModel, report: VerificationReport) -> list[str]:
    units = {v.symbol: v.unit for v in model.variables}
    lines = []
    for target, value in report.sympy_numeric_answers.items():
        lines.append(f"{sp.latex(sp.Symbol(target))} = {_number_tex(value)}{_unit_tex(units.get(target))}")
    return lines


def build_latex(model: ProblemModel, report: VerificationReport,
                steps_by_target: dict[str, list[SolutionStep]] | None = None,
                include_steps: bool = False) -> str:
    """LaTeX source for the derived equations and the answers (and, if asked, each target's steps)."""
    out = ["% Math Representation System -- paste into a document that loads amsmath.", ""]
    eq_lines = equation_latex_lines(model)
    if eq_lines:
        out += ["% Derived equations", r"\begin{gather*}", " \\\\\n".join(f"  {l}" for l in eq_lines),
                r"\end{gather*}", ""]
    ans = answer_latex_lines(model, report)
    if ans:
        out += ["% Verified results", r"\begin{gather*}", " \\\\\n".join(f"  {l}" for l in ans),
                r"\end{gather*}", ""]
    if include_steps and steps_by_target:
        for target, steps in steps_by_target.items():
            out += [f"% Solving for {tex_escape(target)}", r"\begin{gather*}",
                    " \\\\\n".join(f"  {s.expression}" for s in steps), r"\end{gather*}", ""]
    if not eq_lines and not ans:
        out.append("% (nothing to export: no parsed equations and no numeric answers)")
    return "\n".join(out).rstrip() + "\n"


def build_plain_text(model: ProblemModel, report: VerificationReport, problem_text: str = "") -> str:
    """A short plain-text summary: the problem, the answers with units, and the verification verdict."""
    units = {v.symbol: v.unit for v in model.variables}
    cr = report.confidence_report()
    lines = []
    if problem_text.strip():
        lines += [problem_text.strip(), ""]
    if report.sympy_numeric_answers:
        lines.append("Results:")
        for target, value in report.sympy_numeric_answers.items():
            unit = units.get(target)
            lines.append(f"  {target} = {value:.6g}" + (f" {unit}" if unit else ""))
    else:
        lines.append("Results: no single numeric answer (see the derived equations).")
    lines.append("")
    lines.append(f"Verification: {'passed' if cr.passed else 'FAILED'}, "
                 f"confidence {cr.score:.0%} ({cr.label}); {cr.passed_count} of {cr.total_count} checks passed.")
    if model.assumptions:
        lines.append("Assumptions: " + "; ".join(model.assumptions))
    return "\n".join(lines) + "\n"
